### ISSUE TITLE
M1 notebooks supposedly fail the test

### ISSUE THREAD

**Issue by MrCsabaToth** [CsabaConsulting/DetectMobileTest#1]
Reported by https://stackoverflow.com/users/195124/zafer at https://stackoverflow.com/questions/58344491/request-browser-ismobiledevice-not-working-with-ipadair2-and-ios-13-0-1/60553965#comment116358756_60553965

So the solution is indeed brittle. The big question is are there any M1 notebooks which have touch screen. If there aren't then we can weed them out by testing on "navigator.maxTouchPoints > 1" as advised by Zafer.

**Comment by MrCsabaToth** [comment]
@Zafer says that M1 notebooks are not touch capable so far.

**Comment by MrCsabaToth** [comment]
I need a user input about what an M1 Mac displays now for platform and touch points

**Comment by MrCsabaToth** [comment]
Tom supplied me with data about M1 (MBP 17,1 a 13 inch 16GB M1):
> Platform: MacIntel
> Touch Points: 0

**Comment by MrCsabaToth** [comment]
Ok, so the current version might not be sufficient, because it deems the M1 MacBook as a mobile device according to Tom's test:

> Detect Mobile Browser
Platform: MacIntel
Touch Points: 0
Regex: false
iOS Lie: true
Verdict (regex || lie): true
Is Android? false
Is Mobile? false
 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0

**Comment by MrCsabaToth** [comment]
For reference here is an old iPad iOS 14.7.1 with Safari:

> Detect Mobile Browser
Platform: MacIntel
Touch Points: 5
Regex: false
iOS Lie: true
Verdict (regex || lie): true
Is Android? false
Is Mobile? false
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15

**Comment by krkaa** [comment]
Any thoughts on how to determine the device in server side rendering?

**Comment by MrCsabaToth** [comment]
> Any thoughts on how to determine the device in server side rendering?

You can access the user agent string on server side through `Context.Request.Headers["User-Agent"]` (https://stackoverflow.com/questions/37206185/server-side-detection-if-the-browser-is-internet-explorer-in-asp-net-core) or `Request.Headers["User-Agent"]` (https://stackoverflow.com/questions/28664770/how-to-get-user-browser-name-user-agent-in-asp-net-core) and there's even such a thing as `Request.Browser.IsMobileDevice` (https://stackoverflow.com/questions/1829089/how-does-ismobiledevice-work), however you will never be able to diversify as much as you can on the client side. Good example for this is the iOS 13 "lie" detector which instantiates WebGL canvas - you wont be able to do that on server side: https://github.com/CsabaConsulting/DetectMobileTest/blob/master/index.html#L27

So if you are OK that there could be edge cases (if we can call that edge case that all iOS 13 handheld would be considered desktop) then server side solution could be OK for you. I can also imagine a mechanism which would miss these edge cases only at the first request, but then all subsequent requests (button presses) could send info to the server (like the lie detector test result) so from then on you could access that on the server side, that would be all custom code (sending it with the session data, picking it up in some generic request handling method along the pipeline and converting it into simple consumable boolean for the rest to the server code...
